/**
 * Label definitions for GitHub issues.
 * This file serves as the single source of truth for all labels used in the rig-cli system.
 */

/**
 * Component labels - indicate which part of the system an issue affects
 */
export const COMPONENT_LABELS = {
  BACKEND: 'backend',
  FRONTEND: 'frontend',
  FULLSTACK: 'fullstack',
  DEVNET: 'devnet',
  NODE: 'node',
  INFRA: 'infra',
  SERVERLESS: 'serverless',
} as const;

/**
 * Priority labels - indicate urgency/importance
 */
export const PRIORITY_LABELS = {
  P0: 'P0',
  P1: 'P1',
  P2: 'P2',
  P3: 'P3',
  P4: 'P4',
} as const;

/**
 * Phase labels - indicate project phase
 */
export const PHASE_LABELS = {
  PHASE_1_MVP: 'Phase 1: MVP',
  PHASE_2_ENHANCEMENT: 'Phase 2: Enhancement',
  PHASE_3_POLISH: 'Phase 3: Polish',
} as const;

/**
 * Type labels - indicate the kind of work
 */
export const TYPE_LABELS = {
  BUG: 'bug',
  ENHANCEMENT: 'enhancement',
  FEATURE: 'feature',
  REFACTOR: 'refactor',
  DOCS: 'docs',
  CHORE: 'chore',
  TEST: 'test',
} as const;

/**
 * Status labels - indicate workflow state
 */
export const STATUS_LABELS = {
  NEEDS_TRIAGE: 'needs-triage',
  NEEDS_REVIEW: 'needs-review',
  IN_PROGRESS: 'in-progress',
  BLOCKED: 'blocked',
  READY: 'ready',
} as const;

/**
 * Special labels - rig-specific markers
 */
export const SPECIAL_LABELS = {
  RIG_GENERATED: 'rig-generated',
  RIG_CREATED: 'rig-created',
} as const;

/**
 * All label constants grouped together
 */
export const ALL_LABELS = {
  ...COMPONENT_LABELS,
  ...PRIORITY_LABELS,
  ...PHASE_LABELS,
  ...TYPE_LABELS,
  ...STATUS_LABELS,
  ...SPECIAL_LABELS,
} as const;

/**
 * Union type of all valid label values
 */
export type ValidLabel = (typeof ALL_LABELS)[keyof typeof ALL_LABELS];

/**
 * Label details with color and description for GitHub label creation.
 */
export const LABEL_DETAILS: Record<string, { color: string; description: string }> = {
  // Component labels (blue shades)
  [COMPONENT_LABELS.BACKEND]: { color: '0052cc', description: 'Backend service changes' },
  [COMPONENT_LABELS.FRONTEND]: { color: '1d76db', description: 'Frontend UI changes' },
  [COMPONENT_LABELS.FULLSTACK]: { color: '0e8a16', description: 'Full-stack changes across backend and frontend' },
  [COMPONENT_LABELS.DEVNET]: { color: '006b75', description: 'Development network changes' },
  [COMPONENT_LABELS.NODE]: { color: '0075ca', description: 'Node.js project changes' },
  [COMPONENT_LABELS.INFRA]: { color: '5319e7', description: 'Infrastructure and deployment changes' },
  [COMPONENT_LABELS.SERVERLESS]: { color: '1d76db', description: 'Serverless function changes' },
  // Priority labels (red shades — P0 darkest, P4 lightest)
  [PRIORITY_LABELS.P0]: { color: 'b60205', description: 'Critical — drop everything' },
  [PRIORITY_LABELS.P1]: { color: 'd93f0b', description: 'High priority' },
  [PRIORITY_LABELS.P2]: { color: 'e99695', description: 'Medium priority' },
  [PRIORITY_LABELS.P3]: { color: 'f9d0c4', description: 'Low priority' },
  [PRIORITY_LABELS.P4]: { color: 'fef2c0', description: 'Nice to have' },
  // Phase labels (purple)
  [PHASE_LABELS.PHASE_1_MVP]: { color: '5319e7', description: 'Phase 1: Minimum viable product' },
  [PHASE_LABELS.PHASE_2_ENHANCEMENT]: { color: '7057ff', description: 'Phase 2: Feature enhancements' },
  [PHASE_LABELS.PHASE_3_POLISH]: { color: 'a78bfa', description: 'Phase 3: Polish and refinement' },
  // Type labels (varied)
  [TYPE_LABELS.BUG]: { color: 'd73a4a', description: 'Something isn\'t working' },
  [TYPE_LABELS.ENHANCEMENT]: { color: 'a2eeef', description: 'Improvement to existing feature' },
  [TYPE_LABELS.FEATURE]: { color: '0e8a16', description: 'New feature or request' },
  [TYPE_LABELS.REFACTOR]: { color: 'fbca04', description: 'Code refactoring' },
  [TYPE_LABELS.DOCS]: { color: '0075ca', description: 'Documentation changes' },
  [TYPE_LABELS.CHORE]: { color: 'cfd3d7', description: 'Maintenance and chores' },
  [TYPE_LABELS.TEST]: { color: 'bfd4f2', description: 'Test-related changes' },
  // Status labels (yellow/orange)
  [STATUS_LABELS.NEEDS_TRIAGE]: { color: 'fbca04', description: 'Needs triage and prioritization' },
  [STATUS_LABELS.NEEDS_REVIEW]: { color: 'f9d0c4', description: 'Ready for code review' },
  [STATUS_LABELS.IN_PROGRESS]: { color: 'e4e669', description: 'Currently being worked on' },
  [STATUS_LABELS.BLOCKED]: { color: 'd93f0b', description: 'Blocked by another issue or dependency' },
  [STATUS_LABELS.READY]: { color: '0e8a16', description: 'Ready to be picked up' },
  // Special labels (gray)
  [SPECIAL_LABELS.RIG_GENERATED]: { color: 'ededed', description: 'Generated by rig CLI' },
  [SPECIAL_LABELS.RIG_CREATED]: { color: 'ededed', description: 'Created by rig CLI' },
};

/**
 * Helper function to check if a string is a valid label
 */
export function isValidLabel(label: string): label is ValidLabel {
  return Object.values(ALL_LABELS).includes(label as ValidLabel);
}

/**
 * Helper function to get all valid label values as an array
 */
export function getAllValidLabels(): ValidLabel[] {
  return Object.values(ALL_LABELS);
}

/**
 * Returns all label details as an array suitable for GitHub label creation.
 */
export function getLabelDetails(): { name: string; color: string; description: string }[] {
  return Object.entries(LABEL_DETAILS).map(([name, details]) => ({
    name,
    color: details.color,
    description: details.description,
  }));
}
